#!/bin/bash

# Source the config file using an absolute path
source "$(dirname "$(readlink -f "$0")")/../path-config.sh"

# Define the log directories and files using the sourced paths
CHROMIUM_LOG_DIR="$PLAYER_LOGS_DIR/chromium_log"
CHROME_LOG_FILE="$HOME/.config/chromium/chrome_debug.log"
TODAY=$(date +"%Y-%m-%d")
CONSOLE_LOG_FILE="$CHROMIUM_LOG_DIR/$TODAY.log"

mkdir -p "$CHROMIUM_LOG_DIR"
touch "$CONSOLE_LOG_FILE"

# Generate the log start message
LOG_START_MSG="### $(date +"%Y-%m-%d %H:%M:%S") - Chromium log monitoring script started ###"

# Calculate the length of the log start message
MSG_LENGTH=${#LOG_START_MSG}

# Generate a line of '#' characters of the same length
LINE=$(printf '%*s' "$MSG_LENGTH" | tr ' ' '#')

# Log the script run with timestamp. Add a new line before the log entry.
echo -e "\n$LINE\n$LOG_START_MSG\n$LINE\n" >>"$CONSOLE_LOG_FILE"

# Wait for slideshow-player to start and Chromium log file to exist
while true; do
    if pgrep "slideshow-playe" >/dev/null; then
        if [ -f "$CHROME_LOG_FILE" ]; then
            break
        else
            echo "Waiting for Chromium log file to exist..."
        fi
    else
        echo "Waiting for slideshow-player to start..."
    fi
    sleep 1
done

# Continuously extract console logs from Chromium's log file to the daily log file
tail --follow=name "$CHROME_LOG_FILE" | grep --line-buffered 'INFO:CONSOLE' >>"$CONSOLE_LOG_FILE"
