#!/bin/bash

# Chromium Log Monitoring Script
CHROMIUM_LOG_DIR="/home/orangepi/player/logs/chromium_log"
CHROME_LOG_FILE="/home/orangepi/.config/chromium/chrome_debug.log"
TODAY=$(date +"%Y-%m-%d")
CONSOLE_LOG_FILE="$CHROMIUM_LOG_DIR/$TODAY.log"

mkdir -p "$CHROMIUM_LOG_DIR"
touch "$CONSOLE_LOG_FILE"

# Log the script run with timestamp. Add a new line before the log entry.
echo -e "\n$(date +"%Y-%m-%d %H:%M:%S") - Chromium log monitoring script started" >> "$CONSOLE_LOG_FILE"

# Continuously extract console logs from Chromium's log file to the daily log file
tail -f "$CHROME_LOG_FILE" | grep --line-buffered 'INFO:CONSOLE' >> "$CONSOLE_LOG_FILE"