#!/bin/bash

# Source the config file using an absolute path
source "$(dirname "$(readlink -f "$0")")/../path-config.sh"

# Define the DISPLAY_CONFIG_FILE using the sourced paths
DISPLAY_CONFIG_FILE="$PLAYER_CONFIG_DIR/display.conf"

# Open the display configuration file in nano
nano "$DISPLAY_CONFIG_FILE"

# Run the display setup script
"$PLAYER_UTIL_SCRIPTS_DIR/display.sh"
