#!/bin/bash

UTIL_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DISPLAY_CONFIG_FILE="$(dirname "$UTIL_SCRIPT_DIR")/config/display.conf"

nano "$DISPLAY_CONFIG_FILE"

"$UTIL_SCRIPT_DIR/display.sh"