#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DISPLAY_CONFIG_FILE="$(dirname "$CURRENT_DIR")/config/display.conf"

nano "$DISPLAY_CONFIG_FILE"

"$CURRENT_DIR/display.sh"