#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/../helpers.sh" || {
  echo "Error: Could not source helpers.sh"
  exit 1
}

# Define the directories to check
declare -a dirs=("chromium_log" "watchdog" "oasync")

# Loop through the directories
for dir in "${dirs[@]}"; do
  # Check if the directory exists
  if [ -d "$PLAYER_LOGS_DIR/$dir" ]; then
    # Find files in the directory that are older than 30 days and delete them
    find "$PLAYER_LOGS_DIR/$dir" -type f -mtime +30 -exec rm {} \;
  else
    echo "Directory $PLAYER_LOGS_DIR/$dir does not exist"
  fi
done
