#!/bin/bash

# Source the config file using an absolute path
source "$(dirname "$(readlink -f "$0")")/../path-config.sh"

# Grant passwordless sudo for all commands temporarily
echo "orangepi ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/temp_orangepi >/dev/null

# Run the original setup script
"$PLAYER_ROOT_DIR/setup.sh"

# Remove the temporary passwordless sudo
sudo rm /etc/sudoers.d/temp_orangepi
