#!/bin/bash

source "$(dirname "$(readlink -f "$0")")/../helpers.sh" || {
	echo "Error: Could not source helpers.sh"
	exit 1
}

# Grant passwordless sudo for all commands temporarily
echo "orangepi ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/temp_orangepi >/dev/null

# Run the original setup script
"$PLAYER_ROOT_DIR/setup.sh"

# Remove the temporary passwordless sudo
sudo rm /etc/sudoers.d/temp_orangepi
