#!/bin/bash

UTIL_SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR="$(dirname "$UTIL_SCRIPT_DIR")"

# Grant passwordless sudo for all commands temporarily
echo "orangepi ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/temp_orangepi > /dev/null

# Run the original setup script
"$ROOT_DIR/setup.sh"

# Remove the temporary passwordless sudo
sudo rm /etc/sudoers.d/temp_orangepi